### ISSUE TITLE
Just a helping hand passing by! :)

### ISSUE THREAD

**Issue by AntonioVdlC** [tootsuite/mastodon-native#2]
Hi @Gargron and @ineffyble! 👋 

I'm really enjoy Mastodon so far (even though I didn't make the cut into mastodon.social) and I was wondering if you were still planning on advancing the mobile apps? 

I'm using Mastodon on my browser on my phone and it works great, but I was just wondering if you would like some help with this! I just got the code running on my computer (both iOS and Android) and I do know a bit of JavaScript so that can come in handy!

Just let me know! 🙂
Cheers!

**Comment by Gargron** [comment]
I have invested a lot of time contributing to Tusky for Android. There is also Amaroq for iOS, and a couple more. This particular repository is a very barebones boilerplate for an app that can sign in using the Mastodon API and OAuth2.

**Comment by AntonioVdlC** [comment]
Makes sense! 🙂 
Thanks again for Mastodon, it's dope!
