### ISSUE TITLE
repo status check

### ISSUE THREAD

**Issue by borysn** [tootsuite/mastodon-native#4]
hi

i like what you guys are doing, i'm interested in contributing. I did see mastadon.social opened back up, so I joined. I poked around, and saw this repo

honestly I'm a bit confused about the status of mastadon in general, but I'd just like to start by understand the status of this repo. 

no commits for four months, so I'm assuming maybe there's an api redesign or something else halting progress?

I guess I'm asking for the favor of being looped in out of curiosity for contribution

**Comment by ineffyble** [comment]
Hey, this repo is essentially abandoned - it was never developed very far. There's several open-source third-party Mastodon mobile apps I'd encourage you to get involved with if you're interested.

**Comment by borysn** [comment]
@ineffyble I gotcha, thank you!

**Comment by brucelane** [comment]
I will write my own react-native mastodon app then

**Comment by ineffyble** [comment]
@brucelane Happy to accept PRs if you wanted to fork this app - there's just no ongoing development currently.
